on: [workflow_dispatch]
name: Sync Images
jobs:
  sync_images:
    name: Sync Images
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
    
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
          
      - name: Setup Node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: 19.6.0
          
      - name: Run code to Sync Images
        working-directory: ./.github/workflows/utility
        run: node sync_images.mjs
      
      - name: Add Commit Push
        uses: devops-infra/action-commit-push@b7477769b20d4ee5ce9a0ed850a2a93f4725aef3 # master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          add_timestamp: false
          commit_prefix: "[AUTO]"
          commit_message: "Sync Images"
          force: false
          target_branch: update/images
      
      - name: Create A PR
        uses: devops-infra/action-pull-request@3f1cdfa7c7976f6302e820e2b391e846d933693c # v0.4.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: update/images
          target_branch: master
          title: Sync Images
          body: "**Automated pull request**"
          old_string: "**THIS IS AN AUTOMATED UPDATE OF IMAGES**"
          new_string: "** Automatic pull request**"
          get_diff: true
          ignore_users: "dependabot"
