on: [pull_request, workflow_dispatch]
name: PR workflow
jobs:
  validate_chainjson:
    name: Validate edited chains.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3

      - name: Install JSON-Schema-Validator
        run: npm install -g jsonschema

      - name: Validate Chain.json schema
        run: |
          for file in $(find . -name 'chain.json' | grep -v '_template/'); do
            if ! jsonschema -i "$file" ./chain.schema.json; then
              exit 1
            fi
          done
